#!/usr/bin/env python3
"""
Test script for JSON parsing functionality.

This script tests the extract_json function with various sample outputs
that might be generated by the llama8b model.
"""

import sys
from pathlib import Path

# Add src to path
sys.path.append(str(Path(__file__).parent / "src"))

from core.AskCorpus import extract_json

def test_json_parsing():
    """Test JSON parsing with various sample outputs."""
    print("🧪 Testing JSON Parsing Function")
    print("=" * 50)
    
    # Test cases with different formats that llama8b might produce
    test_cases = [
        {
            "name": "Standard JSON array",
            "input": '[{"question": "What is AI?", "answer": "AI is artificial intelligence."}, {"question": "Who invented it?", "answer": "Many researchers contributed to AI development."}]',
            "expected": 2
        },
        {
            "name": "JSON in markdown code block",
            "input": '```json\n[{"question": "What is AI?", "answer": "AI is artificial intelligence."}]\n```',
            "expected": 1
        },
        {
            "name": "JSON with extra text",
            "input": 'Here are the generated questions and answers:\n[{"question": "What is AI?", "answer": "AI is artificial intelligence."}]',
            "expected": 1
        },
        {
            "name": "JSON with prefix and suffix",
            "input": 'Generated questions and answers:\n[{"question": "What is AI?", "answer": "AI is artificial intelligence."}]\nThat\'s all the questions.',
            "expected": 1
        },
        {
            "name": "Multiple JSON arrays (should get first one)",
            "input": '[{"question": "What is AI?", "answer": "AI is artificial intelligence."}] and also [{"question": "Another question?", "answer": "Another answer."}]',
            "expected": 1
        },
        {
            "name": "Nested JSON structure",
            "input": '{"data": [{"question": "What is AI?", "answer": "AI is artificial intelligence."}]}',
            "expected": None  # Should fail as it's not a direct array (this is correct behavior)
        },
        {
            "name": "Malformed JSON",
            "input": '[{"question": "What is AI?", "answer": "AI is artificial intelligence."}, {"question": "Who invented it?"}]',  # Missing answer
            "expected": None
        },
        {
            "name": "Empty response",
            "input": '',
            "expected": None
        },
        {
            "name": "Non-JSON response",
            "input": 'I cannot generate questions for this text.',
            "expected": None
        },
        {
            "name": "JSON with extra whitespace",
            "input": '   [   {"question": "What is AI?", "answer": "AI is artificial intelligence."}   ]   ',
            "expected": 1
        }
    ]
    
    passed = 0
    failed = 0
    
    for i, test_case in enumerate(test_cases, 1):
        print(f"\n📝 Test {i}: {test_case['name']}")
        print(f"Input: {test_case['input'][:100]}{'...' if len(test_case['input']) > 100 else ''}")
        
        result = extract_json(test_case['input'])
        
        if test_case['expected'] is None:
            # Should fail
            if result is None:
                print("✅ PASS - Correctly returned None")
                passed += 1
            else:
                print(f"❌ FAIL - Expected None but got: {len(result) if result else 'None'} items")
                failed += 1
        else:
            # Should succeed with expected number of items
            if result is not None and len(result) == test_case['expected']:
                print(f"✅ PASS - Correctly extracted {len(result)} items")
                passed += 1
            else:
                print(f"❌ FAIL - Expected {test_case['expected']} items but got: {len(result) if result else 'None'}")
                if result:
                    print(f"   Result: {result}")
                failed += 1
    
    print("\n" + "=" * 50)
    print(f"📊 Test Results: {passed} passed, {failed} failed")
    
    if failed == 0:
        print("🎉 All tests passed!")
    else:
        print("❌ Some tests failed. The JSON parsing function may need improvement.")
    
    return failed == 0

def test_with_real_llm_output():
    """Test with actual LLM output if vLLM is running."""
    print("\n🧪 Testing with Real LLM Output")
    print("-" * 30)
    
    try:
        import requests
        response = requests.get("http://localhost:8000/v1/models", timeout=5)
        if response.status_code != 200:
            print("❌ vLLM server is not running")
            return False
    except:
        print("❌ vLLM server is not accessible")
        return False
    
    try:
        from core.AskCorpus import call_vllm_with_retry
        import asyncio
        
        # Test with a simple prompt
        test_prompt = """
You are a **question generation and answering assistant**.  

## Objective  
- Analyze the given **chunk of English text**.  
- Generate a **complete set of natural, single-hop questions** and their answers.  
- Ensure the questions and answers together **fully cover all knowledge points (entities, facts, and ideas)** in the text.  
- Generate questions that cover **all knowledge contained in the text** as completely as possible (no missing entities, facts, or ideas).  
- Only generate questions and answers **directly based on the given text**. Do not make up, infer, or introduce outside information.  
- All generated content must be **safe, harmless, and non-toxic**. Do not produce questions or answers that contain harmful, unsafe, offensive, or illegal content.  

## Question Requirements  
1. Each question must address **only one knowledge point** (no combined or multi-part questions).  
   - Good: "Who discovered penicillin?"  
   - Bad: "Who discovered penicillin and when was it discovered?"  
2. All questions must be **directly answerable** from the text.  
3. Use **explicit noun references** (no vague pronouns like "he," "it," "they").  
4. Questions must be **non-redundant, clear, and concise**.  
5. Ensure that **every entity, event, and idea mentioned in the text** is represented in at least one question.  

## Output Format  
- Return the result as a **JSON array** inside a markdown code block.  
- Each element of the array must be an object containing a `"question"` and an `"answer"`.  
- The array must be **flat** (no nested arrays or objects).  
- The output must be **machine-readable JSON** (double quotes around keys and string values).  

### Example Output
```json
[
  {{"question": "Who discovered penicillin?", "answer": "Alexander Fleming discovered penicillin."}},
  {{"question": "When was penicillin discovered?", "answer": "Penicillin was discovered in 1928."}},
  {{"question": "Where was penicillin discovered?", "answer": "Penicillin was discovered in London."}},
  {{"question": "How was penicillin discovered?", "answer": "Penicillin was discovered when Alexander Fleming observed mold killing bacteria."}},
  {{"question": "Why was the discovery of penicillin important?", "answer": "The discovery of penicillin was important because it led to the development of antibiotics."}},
]

The chunk is:
Alexander Fleming was a Scottish biologist and pharmacologist. He discovered penicillin in 1928 at St. Mary's Hospital in London. This discovery revolutionized medicine and led to the development of antibiotics.
"""
        
        print("🔄 Calling vLLM with test prompt...")
        result = asyncio.run(call_vllm_with_retry(test_prompt))
        
        if result:
            print(f"✅ LLM response received (length: {len(result)})")
            print(f"📄 Response preview: {result[:200]}...")
            
            # Test JSON extraction
            json_result = extract_json(result)
            if json_result:
                print(f"✅ JSON extraction successful: {len(json_result)} QA pairs")
                if json_result:
                    print(f"📝 First QA pair: {json_result[0]}")
                return True
            else:
                print("❌ JSON extraction failed")
                print(f"📄 Full response: {result}")
                return False
        else:
            print("❌ No response from LLM")
            return False
            
    except Exception as e:
        print(f"❌ Error testing with real LLM: {e}")
        return False

def main():
    """Main test function."""
    print("🚀 JSON Parsing Test Suite")
    print("=" * 50)
    
    # Test with sample data
    sample_tests_passed = test_json_parsing()
    
    # Test with real LLM output
    real_tests_passed = test_with_real_llm_output()
    
    print("\n" + "=" * 50)
    print("📊 Final Results:")
    print(f"📝 Sample tests: {'✅ PASS' if sample_tests_passed else '❌ FAIL'}")
    print(f"🤖 Real LLM tests: {'✅ PASS' if real_tests_passed else '❌ FAIL'}")
    
    if sample_tests_passed and real_tests_passed:
        print("\n🎉 All tests passed! JSON parsing is working correctly.")
    else:
        print("\n❌ Some tests failed. Check the JSON parsing function.")

if __name__ == "__main__":
    main()
